# 该文件保存 UMI 相机物理端口、MJPEG 模式及图像输出参数。
/**:
  ros__parameters:
    video_device: /dev/v4l/by-path/pci-0000:85:00.0-usb-0:4:1.0-video-index0
    width: 1920
    height: 1080
    fps: 30
    frame_id: usb_camera_optical_frame
    publish_compressed: false
